### ISSUE TITLE
The OPENAI_API_KEY environment variable is missing or empty;

### ISSUE THREAD

**Issue by vikas2131** [charlesyu108/voiceai-js-starter#7]
Even after adding a .env file with openAI API key. It still throws this error.

**Comment by vikas2131** [comment]
I figured out the problem, It was due to the `dotenv.config();` being written after `const { Assistant } = require("./lib/assistant");` at line 5 of index.js in server folder.

**Comment by charlesyu108** [comment]
Thanks for commenting! Ill fix that :^)
